[versions]
agp = "8.8.0"
androidasync = "2.2.1"
kotlin = "1.9.24"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.2.1"
okhttp = "4.9.3"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidasync = { module = "com.koushikdutta.async:androidasync", version.ref = "androidasync" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
